export const estudiantes=[
    {
        id:1,
        nomYape:'Pepe Lopez',
        dni:'12345678',
        curso:'Ing. Sistemas',
        localidad:'Merlo',
        correoElectronico:'pepe@pe.com',
        telefono:'87654321',
        estado:'Activo',
    },
    {
        id:2,
        nomYape:'Juan Perez',
        dni:'87654321',
        curso:'Ing. Sistemas',
        localidad:'Ituzaingo',
        correoElectronico:'juan@ju.com',
        telefono:'12345678',
        estado:'Inactivo',
    },
    {
        id:3,
        nomYape:'Maria Suarez',
        dni:'12345678',
        curso:'Ing. Sistemas',
        localidad:'Once',
        correoElectronico:'maria@ma.com',
        telefono:'87654321',
        estado:'Activo',
    },
    {
        id:4,
        nomYape:'Luisa Perez',
        dni:'87654321',
        curso:'Ing. Sistemas',
        localidad:'Ituzaingo',
        correoElectronico:'luisa@lu.com',
        telefono:'12345678',
        estado:'Inactivo',
    },
    {
        id:5,
        nomYape:'Pedro Rojas',
        dni:'12345678',
        curso:'Ing. Sistemas',
        localidad:'Merlo',
        correoElectronico:'pedro@pe.com',
        telefono:'87654321',
        estado:'Activo',
    },
    {
        id:6,
        nomYape:'Ana Gonzalez',
        dni:'87654321',
        curso:'Ing. Sistemas',
        localidad:'Ituzaingo',
        correoElectronico:'ana@an.com',
        telefono:'12345678',
        estado:'Inactivo',
    },
    {
        id:7,
        nomYape:'Carlos Gomez',
        dni:'12345678',
        curso:'Ing. Sistemas',
        localidad:'Merlo',
        correoElectronico:'carlos@ca.com',
        telefono:'87654321',
        estado:'Activo',
    },
    {
        id:8,
        nomYape:'Lucia Sanchez',
        dni:'87654321',
        curso:'Ing. Sistemas',
        localidad:'Ituzaingo',
        correoElectronico:'lucia@lu.com',
        telefono:'12345678',
        estado:'Inactivo',
    },
    {
        id:9,
        nomYape:'Jorge Garcia',
        dni:'12345678',
        curso:'Ing. Sistemas',
        localidad:'Merlo',
        correoElectronico:'jorge@jo.com',
        telefono:'87654321',
        estado:'Activo',
    },
    {
        id:10,
        nomYape:'Marta Torrez',
        dni:'87654321',
        curso:'Ing. Sistemas',
        localidad:'Ituzaingo',
        correoElectronico:'marta@ma.com',
        telefono:'12345678',
        estado:'Inactivo',
    },
    {
        id:11,
        nomYape:'Pablo Ruiz',
        dni:'12345678',
        curso:'Ing. Sistemas',
        localidad:'Merlo',
        correoElectronico:'pablo@pa.com',
        telefono:'87654321',
        estado:'Activo',
    },
    {
        id:12,
        nomYape:'Sandra Diaz',
        dni:'87654321',
        curso:'Ing. Sistemas',
        localidad:'Ituzaingo',
        correoElectronico:'sandra@sa.com',
        telefono:'12345678',
        estado:'Inactivo',
    },
    {
        id:13,
        nomYape:'Fernando Flores',
        dni:'12345678',
        curso:'Ing. Sistemas',
        localidad:'Merlo',
        correoElectronico:'fernando@fe.com',
        telefono:'87654321',
        estado:'Activo',
    },
    {
        id:14,
        nomYape:'Cristina Alvarez',
        dni:'87654321',
        curso:'Ing. Sistemas',
        localidad:'Ituzaingo',
        correoElectronico:'cristina@cr.com',
        telefono:'12345678',
        estado:'Inactivo',
    },
    {
        id:15,
        nomYape:'Eduardo Acosta',
        dni:'12345678',
        curso:'Ing. Sistemas',
        localidad:'Merlo',
        correoElectronico:'eduardo@ed.com',
        telefono:'87654321',
        estado:'Activo',
    },
    {
        id:16,
        nomYape:'Luisa Fernanda',
        dni:'87654321',
        curso:'Ing. Sistemas',
        localidad:'Ituzaingo',
        correoElectronico:'luisa@lu.com',
        telefono:'12345678',
        estado:'Inactivo',
    },
    {
        id:17,
        nomYape:'Pedro Diaz',
        dni:'12345678',
        curso:'Ing. Sistemas',
        localidad:'Merlo',
        correoElectronico:'pedro@pe.com',
        telefono:'87654321',
        estado:'Activo',
    },
    {
        id:18,
        nomYape:'Ana Perez',
        dni:'87654321',
        curso:'Ing. Sistemas',
        localidad:'Ituzaingo',
        correoElectronico:'ana@an.com',
        telefono:'12345678',
        estado:'Inactivo',
    },
    {
        id:19,
        nomYape:'Carlos Lopez',
        dni:'12345678',
        curso:'Ing. Sistemas',
        localidad:'Merlo',
        correoElectronico:'carlos@ca.com',
        telefono:'87654321',
        estado:'Activo',
    },
    {
        id:20,
        nomYape:'Lucia Sosa',
        dni:'87654321',
        curso:'Ing. Sistemas',
        localidad:'Ituzaingo',
        correoElectronico:'lucia@lu.com',
        telefono:'12345678',
        estado:'Inactivo',
    }
]